### PR TITLE
corrected job secrets

### PR DESCRIPTION
**Pull request by sumanth-lingappa**
Renamed `secrets.AH_TOKEN` to `secrets.ah_token` so that this workflow can be called from other workflows

### CODE REVIEW

**Comment by sumanth-lingappa** [comment]
@ssbarnea, please review this PR. This is blocking our release of `netscaler.adc` through GitHub actions.

We have used this workflow as below

- https://github.com/netscaler/ansible-collection-netscaleradc/blob/main/.github/workflows/release.yml

**Comment by sumanth-lingappa** [comment]
I guess, my changes are not mandatory to this workflow.

Can anyone please help me understand how `secrets.AH_TOKEN` in this repository will fetch `secrets.AH_TOKEN` in my repository?

I was of the impression that the correct way to use is `secrets.ah_token` in this workflow. Please help me understand

**Comment by ssbarnea** [comment]
@sumanth-lingappa Can you please include a link to an article explaining this as this is the first time where I see this. `secrets:` are environment variables, and these are almost always only uppercase. This is how we also defined them, as uppercase.

It is very confusing to refer to environment variables with lowercase.

**Comment by sumanth-lingappa** [comment]
@ssbarnea, I didnt mention them as environment variables. I meant them as `local variables`.

If you see in [in this line](https://github.com/ansible/team-devtools/blob/0e4a7a017c22bbad6ed274a5cb0c21de14b62541/.github/workflows/release_collection.yml#L19), there are local variables -- `secrets.ah_token` and `secrets.ansible_galaxy_api_key`. 

My argument was, we can use these local variables instead of `secrets.AH_TOKEN` (in uppercase).

**Review by ssbarnea — APPROVED** [review]

**Pull request merged**
